config/routes.rb
Rails.application.routes.draw do
  get root to:'homes#top'
  get 'books/new'
  post 'books'=>'books#create'
  get 'books/'=>'books#index'
  get 'books/:id'=>'books#show', as: 'book'
  get 'books/:id/edit'=>'books#edit', as: 'edit_book'
  patch 'books/:id'=>'books#update', as: 'update_book'
  delete 'books/:id'=>'books#destroy', as: 'destroy_book'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence:true
  validates :body, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice]="Book was successfully created."
      redirect_to @book
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else

      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <h2><%=@book.errors.count %> errors prohibited this book from being saved:<h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="field">
  <%= form_with model: @book do |f| %>
     <li>Title</li>
     <%= f.text_field :title %>
    <li>Body</li>
     <%= f.text_area :body %>
     <li></li>
    <div class="submit-button"> <%= f.submit ' Update Book ' %></div>
<% end %>

 <p class="edit-link">
  <%= link_to 'Show', "/books/#{@book.id}" %>
  |
  <%= link_to 'Back', "/books" %>
</p>

app/views/books/index.html.erb
<h1>Books</h1>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <% @books.each do |book| %>
    <tr>
      <td><span><%= book.title %></span></td>
      <td><span><%= book.body %></span></td>
      <td><span><%= link_to 'Show', "/books/#{book.id}" %></span></td>
      <td><span><%= link_to 'Edit', "/books/#{book.id}/edit" %></span></td>
      <td><span><%= link_to 'Destroy', destroy_book_path(book.id), method: :delete, "data-confirm"=>"Are you sure?" %></span></td>
    </tr>
</tbody>
<% end %>
</table>


<h2 class="newbook-title">New Book</h2>

<% if @book.errors.any? %>
  <h2><%= @book.errors.count %> errors prohibited this book from being saved:<h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

 <div class="field">
   <%= form_with model: @book do |f| %>
     <li>Title</li>
     <%= f.text_field :title %>
    <li>Body</li>
     <%= f.text_area :body %>
     <li></li>
     <%= f.submit ' Create Book ' %>
  <% end %>



</div>

app/views/books/show.html.erb
<diV>
  <%= flash[:notice] %>
</diV>

<p class="show-content">
  <strong>Title:</strong>
  <%= @book.title %>
  </p>

<p class="show-content">
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<p>
  <%= link_to 'Edit', "/books/#{@book.id}/edit" %>
  |
  <%= link_to 'Back', "/books" %>
</p>

app/views/homes/top.html.erb
<body>
  <h1>ようこそ <strong>Bookers</strong> へ！</h1>
  <p class="top-sentence"><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
  <p class="top-sentence">印象を共有し交換することができます</p>
  <a class="start-link" href="/books">start</a>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>